models:
  - name: faceboxes

    launchers:
      - framework: dlsdk
        tags:
            - FP32
        model:   faceboxes/caffe2/FP32/faceboxes.xml
        weights: faceboxes/caffe2/FP32/faceboxes.bin
        adapter:
            type: faceboxes
            boxes_out: "342"
            scores_out: "353"

      - framework: dlsdk
        tags:
            - FP16
        model:   faceboxes/caffe2/FP16/faceboxes.xml
        weights: faceboxes/caffe2/FP16/faceboxes.bin
        adapter:
            type: faceboxes
            boxes_out: "342"
            scores_out: "353"

      - framework: dlsdk
        tags:
            - FP32-INT8
        model:   faceboxes/caffe2/FP32-INT8/faceboxes.xml
        weights: faceboxes/caffe2/FP32-INT8/faceboxes.bin
        adapter:
            type: faceboxes
            boxes_out: "342"
            scores_out: "353"

      - framework: dlsdk
        tags:
            - FP16-INT8
        model:   faceboxes/caffe2/FP16-INT8/faceboxes.xml
        weights: faceboxes/caffe2/FP16-INT8/faceboxes.bin
        adapter:
            type: faceboxes
            boxes_out: "342"
            scores_out: "353"

    datasets:
      - name: wider

        preprocessing:
          - type: resize
            dst_width: 1024
            dst_height: 1024

        postprocessing:
          - type: resize_prediction_boxes
          - type: filter
            apply_to: annotation
            height_range: 100
            is_empty: True

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False

global_definitions: ../dataset_definitions.yml
