models:
  - name: openpose-pose-body25

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   openpose-pose-body25.xml
        weights: openpose-pose-body25.bin
        allow_reshape_input: True
        adapter: human_pose_estimation

    datasets:
      - name: ms_coco_keypoints

        preprocessing:
          - type: resize
            size: 16
            interpolation: CUBIC
            aspect_ratio_scale: width
          - type: padding
            stride: 8

        postprocessing:
          - type: filter
            apply_to: annotation
            area_range: 1, 10000000000
          - type: filter
            apply_to: prediction
            area_range: 1, 10000000000

        metrics:
          - name: AP
            type: coco_precision
            max_detections: 20

global_definitions: ../dataset_definitions.yml
 #     annotation_file: /home/annamiro/Downloads/person_keypoints_val2017_foot_v1.json
